### ISSUE TITLE
卡在了加载牌局69进不去 报错

### ISSUE THREAD

**Issue by TanyaRinL** [Avenshy/mahjong-helper-majsoul-mitmproxy#14]
127.0.0.1:62141 <- WebSocket binary message <- gateway-v2.maj-soul.com:443/gateway
[14:17:55.039][127.0.0.1:62112] error establishing server connection: [WinError 121] 信号灯超时时间已到
127.0.0.1:62112: CONNECT accounts.google.com:443
              << 502 Bad Gateway 221b
[14:17:55.043] Traceback (most recent call last):

  File "F:\daima\python\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)

  File "F:\daima\python\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
[14:17:55.044][127.0.0.1:62112] client disconnect
[14:17:55.948][127.0.0.1:62163] client connect****

**Comment by TanyaRinL** [comment]
重启电脑之后好了 但是如果开着雀魂网页 再打开chrome去另外的网页的话就会报错502 Bad Gateway
